apiVersion: apps/v1
kind: Deployment    #类型是一个Deployment
metadata:
  name: nginx-deployment  #唯一标识
spec:
  selector:
    matchLabels:
      app: nginx   #说明该Deplpyment管理所有携带app:nginx标签的POD
  replicas: 2      #副本数为2，即创建两个POD
  template:
    metadata:
      labels:
        app: nginx   #pod标签为app:ngnix
    spec:
      containers:    #容器相关配置
      - name: nginx
        image: nginx:1.8  #从1.7.9改为1.8
        ports:
        - containerPort: 80
        volumeMounts: 
        - mountPath: /usr/share/nginx/html   #配置镜像中挂载的路径
          name: nginx-vol
      volumes:                                 #宿主机中的路径
      - name: nginx-vol
        hostPath:
          path: /home/docker/nginx
          type: DirectoryOrCreate
        # emptyDir: {} 这个是创建临时目录

# 为此，我定义了一个 Pod 模版（spec.template），这个模版描述了我想要创建的 Pod 的细节。
# 在上面的例子里，这个 Pod 里只有一个容器，这个容器的镜像（spec.containers.image）是 nginx:1.7.9，
# 这个容器监听端口（containerPort）是 80。
