/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BuilderView: typeof import('./src/components/BuilderView.vue')['default']
    DesignView: typeof import('./src/components/DesignView.vue')['default']
    NutCell: typeof import('@nutui/nutui')['Cell']
    NutEcard: typeof import('@nutui/nutui')['Ecard']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
