/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NutDivider: typeof import('@nutui/nutui')['Divider']
    NutImage: typeof import('@nutui/nutui')['Image']
  }
}
